sudo: false

dist: trusty

language: php

## Cache composer downloads.
cache:
  apt: true
  directories:
    - $HOME/.cache/composer/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
      addons:
        apt:
          packages:
            - libxml2-utils
    - php: 5.4

before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - export XMLLINT_INDENT="    "
  - composer install
  - vendor/bin/phpcs -i

script:
  - |
    if [[ $TRAVIS_PHP_VERSION == "7.3" ]]; then
      # Validate the xml files.
      # @link http://xmlsoft.org/xmllint.html
      xmllint --noout ./*/ruleset.xml

      # Check the code-style consistency of the xml files.
      diff -B ./PHPCompatibilityParagonieRandomCompat/ruleset.xml <(xmllint --format "./PHPCompatibilityParagonieRandomCompat/ruleset.xml")
      diff -B ./PHPCompatibilityParagonieSodiumCompat/ruleset.xml <(xmllint --format "./PHPCompatibilityParagonieSodiumCompat/ruleset.xml")
    fi

  # Test the rulesets.
  - vendor/bin/phpcs ./Test/ParagonieRandomCompatTest.php --standard=PHPCompatibilityParagonieRandomCompat --runtime-set testVersion 5.2-
  - vendor/bin/phpcs ./Test/ParagonieSodiumCompatTest.php --standard=PHPCompatibilityParagonieSodiumCompat --runtime-set testVersion 5.3-

  # Check that the rulesets don't throw unnecessary errors for the compat libraries themselves.
  - vendor/bin/phpcs ./vendor/paragonie/random_compat/ --standard=PHPCompatibilityParagonieRandomCompat --runtime-set testVersion 5.2- --ignore=/random_compat/tests/*,/random_compat/other/*
  - vendor/bin/phpcs ./vendor/paragonie/sodium_compat/ --standard=PHPCompatibilityParagonieSodiumCompat --runtime-set testVersion 5.3- --ignore=/sodium_compat/tests/*

  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict
